# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-09-16 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('yearpublished', models.IntegerField(blank=True)),
                ('description', models.TextField()),
                ('image', models.URLField(null=True)),
                ('thumbnail', models.URLField(null=True)),
                ('playingtime', models.IntegerField()),
                ('designers', models.CharField(blank=True, max_length=512)),
                ('publishers', models.CharField(blank=True, max_length=512)),
                ('mechanics', models.CharField(blank=True, max_length=512)),
                ('categories', models.CharField(blank=True, max_length=512)),
                ('minplayers', models.IntegerField()),
                ('maxplayers', models.IntegerField()),
                ('ratings_usersrated', models.IntegerField()),
                ('ratings_average', models.FloatField()),
                ('ratings_averageweight', models.FloatField()),
                ('bgg_json', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('title', models.CharField(max_length=128)),
                ('aliases', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('en_wiki_url', models.URLField(blank=True)),
                ('wiki_api_data_cache', models.TextField(blank=True)),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wgg.Conflict')),
            ],
        ),
        migrations.CreateModel(
            name='GameToConflict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage', models.IntegerField(default=100)),
                ('conflict', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wgg.Conflict')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wgg.BoardGame')),
            ],
        ),
    ]
